[build]
  command = "npm run build"
  publish = ".next"

[functions]
  node_bundler = "esbuild"
  included_files = ["data/**"]

[build.environment]
  NODE_VERSION = "22"

[[plugins]]
  package = "@netlify/plugin-nextjs"
